"""create test2

Revision ID: 06bdd46d50e0
Revises: 
Create Date: 2023-10-21 22:58:03.557631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06bdd46d50e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('allowed_users_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'user', ['allowed_users_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'allowed_users_id')
    # ### end Alembic commands ###
