"""create test10

Revision ID: 0de454253b08
Revises: 333b3673f30b
Create Date: 2023-10-22 10:59:51.969976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0de454253b08'
down_revision: Union[str, None] = '333b3673f30b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Product_User',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['Product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ProductUser')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ProductUser',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"ProductUser_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['Product.id'], name='ProductUser_product_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='ProductUser_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ProductUser_pkey')
    )
    op.drop_table('Product_User')
    # ### end Alembic commands ###
