"""create test13

Revision ID: cb16920a6699
Revises: 60f937893c5d
Create Date: 2023-10-22 16:43:42.931822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb16920a6699'
down_revision: Union[str, None] = '60f937893c5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Lesson', sa.Column('product_id', sa.Integer(), nullable=True))
    op.drop_constraint('Lesson_products_id_fkey', 'Lesson', type_='foreignkey')
    op.create_foreign_key(None, 'Lesson', 'Product', ['product_id'], ['id'])
    op.drop_column('Lesson', 'products_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Lesson', sa.Column('products_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Lesson', type_='foreignkey')
    op.create_foreign_key('Lesson_products_id_fkey', 'Lesson', 'Product', ['products_id'], ['id'])
    op.drop_column('Lesson', 'product_id')
    # ### end Alembic commands ###
