"""create test14

Revision ID: f498dd369e33
Revises: cb16920a6699
Create Date: 2023-10-22 17:03:56.308822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f498dd369e33'
down_revision: Union[str, None] = 'cb16920a6699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Lesson_product_id_fkey', 'Lesson', type_='foreignkey')
    op.create_foreign_key(None, 'Lesson', 'Product', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Lesson', type_='foreignkey')
    op.create_foreign_key('Lesson_product_id_fkey', 'Lesson', 'Product', ['product_id'], ['id'])
    # ### end Alembic commands ###
